SELECT
    Id , OwnerId , IsDeleted , Name , CurrencyIsoCode , CreatedDate , CreatedById , LastModifiedDate , LastModifiedById , SystemModstamp , LastActivityDate , LastViewedDate , LastReferencedDate , ConnectionReceivedId , ConnectionSentId , LLC_BI__Active__c , LLC_BI__Compliance_Days_Prior__c , LLC_BI__Covenant_Type__c , LLC_BI__Days_Past_Next_Evaluation__c , LLC_BI__Days_Until_Next_Evaluation__c , LLC_BI__Detail__c , LLC_BI__Financial_Indicator_Value__c , LLC_BI__Frequency_Months__c , LLC_BI__Frequency__c , LLC_BI__Is_Template__c , LLC_BI__Last_Evaluation_Date__c , LLC_BI__Last_Evaluation_Status__c , LLC_BI__Next_Evaluation_Date__c , LLC_BI__Notes__c , LLC_BI__Required__c , LLC_BI__lookupKey__c , Relationship__c , LLC_BI__Effective_Date__c , LLC_BI__Linked_Spread_Statement_Record_Total__c , LLC_BI__Linked_Spread_Statement_Record__c , LLC_BI__Related_Covenant__c , Migration_ID__c , Integration_Source__c , LLC_BI__Comments__c , isTest__c , LLC_BI__Account__c , LLC_BI__Due_Date__c , CCS_Action__c , CCS_Bank_Entity__c , CCS_Covenant_Type__c , CCS_Description__c , CCS_Entity_Tested__c , CCS_Grace_Period_Days__c , CCS_IsFacilityBooked__c , CCS_Measure__c , CCS_Period_End__c , CCS_Restricted_User__c , CCS_Rolling_12M__c , CCS_State__c , CCS_Status__c , CCS_Test_Status__c , CCS_Tested_Against__c , CCS_Value__c , Covenant_Mgmt__c , CCS_Defination__c
FROM dmn01-rsksoi-bld-01-2017.dmn01_rsksoi_euwe2_rsk_csp_downstream_raw.rskcsp_ds_covenant2
UNION ALL
SELECT
    Id, OwnerId, IsDeleted, Name, CurrencyIsoCode, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, LastActivityDate, LastViewedDate, LastReferencedDate, ConnectionReceivedId, ConnectionSentId, LLC_BI__Active__c, LLC_BI__Compliance_Days_Prior__c, LLC_BI__Covenant_Type__c, LLC_BI__Days_Past_Next_Evaluation__c, LLC_BI__Days_Until_Next_Evaluation__c, LLC_BI__Detail__c, LLC_BI__Financial_Indicator_Value__c, LLC_BI__Frequency_Months__c, LLC_BI__Frequency__c, LLC_BI__Is_Template__c, LLC_BI__Last_Evaluation_Date__c, LLC_BI__Last_Evaluation_Status__c, LLC_BI__Next_Evaluation_Date__c, LLC_BI__Notes__c, LLC_BI__Required__c, LLC_BI__lookupKey__c, Relationship__c, LLC_BI__Effective_Date__c, LLC_BI__Linked_Spread_Statement_Record_Total__c, LLC_BI__Linked_Spread_Statement_Record__c, LLC_BI__Related_Covenant__c, Migration_ID__c, Integration_Source__c, LLC_BI__Comments__c, isTest__c, LLC_BI__Account__c, LLC_BI__Due_Date__c, CCS_Action__c, CCS_Bank_Entity__c, CCS_Covenant_Type__c, CCS_Description__c, CCS_Entity_Tested__c, CCS_Grace_Period_Days__c, CCS_IsFacilityBooked__c, CCS_Measure__c, CCS_Period_End__c, CCS_Restricted_User__c, CCS_Rolling_12M__c, CCS_State__c, CCS_Status__c, CCS_Test_Status__c, CCS_Tested_Against__c, CCS_Value__c, Covenant_Mgmt__c, CCS_Defination__c
FROM dmn01-rsksoi-bld-01-2017.dmn01_rsksoi_euwe2_rsk_csp_ds_staging.rskcsp_ds_covenant2_staging;


