 INSERT INTO dmn01-rsksoi-bld-01-2017.dmn01_rsksoi_euwe2_rsk_csp_downstream_raw.rskcsp_ds_loan_covenant  --  INSERT
 (
  ReplayId,
  ChangeEventHeader,
  Id,
  IsDeleted,
  Name,
  CurrencyIsoCode,
  CreatedDate,
  CreatedById,
  LastModifiedDate,
  LastModifiedById,
  SystemModstamp,
  LastActivityDate,
  ConnectionReceivedId,
  ConnectionSentId,
  LLC_BI__Covenant2__c,
  LLC_BI__Loan__c,
  LLC_BI__Active__c,
  CCS_UserProfile__c,
  CCS_Restricted_User__c,
  _ObjectType,
  _EventType
)
VALUES
(
  "a1w2600000FxwrzAAB",
  STRUCT
    <entityName STRING,
    recordIds	ARRAY<STRING>,
    _changeType	STRING,
    _changedFields	ARRAY<STRING>,
    changeOrigin	STRING,
    transactionKey	STRING,
    sequenceNumber	INTEGER,
    commitTimestamp	INTEGER,
    commitUser	STRING,
    commitNumber INTEGER
    >(
      'entityName',
      ["a1w2600000FxwrzAAB"],
      "INSERT",
      ["LastModifiedDate"],
      "com/salesforce/api/soap/56.0;client=SfdcInternalAPI/",
      "0001dcd1-98ee-76c7-76c8-502452548cff",
      1,
      1671458063000,
      "00526000009uyrWAAQ",
      11010485985695
    )
  ,
  'STRING', -- Id
  FALSE, -- IsDeleted
  'STRING', -- Name
  NULL, -- CurrencyIsoCode
  1671537998000, -- CreatedDate
  'STRING', -- CreatedById
  1671537998000, -- LastModifiedDate
  'STRING', -- LastModifiedById
  1671537998000, -- SystemModstamp
  1671537998000, -- LastActivityDate
  'STRING', -- ConnectionReceivedId
  'STRING', -- ConnectionSentId
  'STRING', -- LLC_BI__Covenant2__c
  'STRING', -- LLC_BI__Loan__c
  FALSE, -- LLC_BI__Active__c
  'STRING', -- CCS_UserProfile__c
  NULL, -- CCS_Restricted_User__c
  "OBJECTTYPE",
  "EVENTTYPE"
);

 INSERT INTO dmn01-rsksoi-bld-01-2017.dmn01_rsksoi_euwe2_rsk_csp_downstream_raw.rskcsp_ds_loan_covenant  --  INSERT 2
 (
     ReplayId,
     ChangeEventHeader,
     Id,
     IsDeleted,
     Name,
     CurrencyIsoCode,
     CreatedDate,
     CreatedById,
     LastModifiedDate,
     LastModifiedById,
     SystemModstamp,
     LastActivityDate,
     ConnectionReceivedId,
     ConnectionSentId,
     LLC_BI__Covenant2__c,
     LLC_BI__Loan__c,
     LLC_BI__Active__c,
     CCS_UserProfile__c,
     CCS_Restricted_User__c,
     _ObjectType,
     _EventType
 )
 VALUES
     (
         "a1w2600000FxwrzAAB",
         STRUCT
             <entityName STRING,
              recordIds	ARRAY<STRING>,
              _changeType	STRING,
              _changedFields	ARRAY<STRING>,
              changeOrigin	STRING,
              transactionKey	STRING,
              sequenceNumber	INTEGER,
              commitTimestamp	INTEGER,
              commitUser	STRING,
              commitNumber INTEGER
                 >(
             'entityName',
             ["a1w2600000FxwrzAAB"],
             "INSERT",
             ["LastModifiedDate"],
             "com/salesforce/api/soap/56.0;client=SfdcInternalAPI/",
             "0001dcd1-98ee-76c7-76c8-502452548cff",
             1,
             1671458063000,
             "00526000009uyrWAAQ",
             11010485985695
             )
         ,
         'STRING1', -- Id
         FALSE, -- IsDeleted
         'STRING1', -- Name
         NULL, -- CurrencyIsoCode
         1671537998000, -- CreatedDate
         'STRING', -- CreatedById
         1671537998000, -- LastModifiedDate
         'STRING', -- LastModifiedById
         1671537998000, -- SystemModstamp
         1671537998000, -- LastActivityDate
         'STRING', -- ConnectionReceivedId
         'STRING', -- ConnectionSentId
         'STRING', -- LLC_BI__Covenant2__c
         'STRING', -- LLC_BI__Loan__c
         FALSE, -- LLC_BI__Active__c
         'STRING', -- CCS_UserProfile__c
         NULL, -- CCS_Restricted_User__c
         "OBJECTTYPE",
         "EVENTTYPE"
     );


 INSERT INTO dmn01-rsksoi-bld-01-2017.dmn01_rsksoi_euwe2_rsk_csp_downstream_raw.rskcsp_ds_loan_covenant  --   UPDATE
 (
     ReplayId,
     ChangeEventHeader,
     Id,
     IsDeleted,
     Name,
     CurrencyIsoCode,
     CreatedDate,
     CreatedById,
     LastModifiedDate,
     LastModifiedById,
     SystemModstamp,
     LastActivityDate,
     ConnectionReceivedId,
     ConnectionSentId,
     LLC_BI__Covenant2__c,
     LLC_BI__Loan__c,
     LLC_BI__Active__c,
     CCS_UserProfile__c,
     CCS_Restricted_User__c,
     _ObjectType,
     _EventType
 )
 VALUES
     (
         "a1w2600000FxwrzAAB",
         STRUCT
             <entityName STRING,
              recordIds	ARRAY<STRING>,
              _changeType	STRING,
              _changedFields	ARRAY<STRING>,
              changeOrigin	STRING,
              transactionKey	STRING,
              sequenceNumber	INTEGER,
              commitTimestamp	INTEGER,
              commitUser	STRING,
              commitNumber INTEGER
                 >(
             'entityName',
             ["a1w2600000FxwrzAAB"],
             "UPDATE",
             ["LastModifiedDate"],
             "com/salesforce/api/soap/56.0;client=SfdcInternalAPI/",
             "0001dcd1-98ee-76c7-76c8-502452548cff",
             1,
             1671458063000,
             "00526000009uyrWAAQ",
             11010485985695
             )
         ,
         'STRING1', -- Id
         FALSE, -- IsDeleted
         'STRING1', -- Name
         'GBP', -- CurrencyIsoCode
         1671537998000, -- CreatedDate
         'STRING1', -- CreatedById
         1671537998000, -- LastModifiedDate
         'STRING', -- LastModifiedById
         1671537998000, -- SystemModstamp
         1671537998000, -- LastActivityDate
         'STRING', -- ConnectionReceivedId
         'STRING', -- ConnectionSentId
         'STRING', -- LLC_BI__Covenant2__c
         'STRING', -- LLC_BI__Loan__c
         FALSE, -- LLC_BI__Active__c
         'STRING', -- CCS_UserProfile__c
         NULL, -- CCS_Restricted_User__c
         "OBJECTTYPE",
         "EVENTTYPE"
     );

 INSERT INTO dmn01-rsksoi-bld-01-2017.dmn01_rsksoi_euwe2_rsk_csp_downstream_raw.rskcsp_ds_loan_covenant  --  INSERT 3
 (
     ReplayId,
     ChangeEventHeader,
     Id,
     IsDeleted,
     Name,
     CurrencyIsoCode,
     CreatedDate,
     CreatedById,
     LastModifiedDate,
     LastModifiedById,
     SystemModstamp,
     LastActivityDate,
     ConnectionReceivedId,
     ConnectionSentId,
     LLC_BI__Covenant2__c,
     LLC_BI__Loan__c,
     LLC_BI__Active__c,
     CCS_UserProfile__c,
     CCS_Restricted_User__c,
     _ObjectType,
     _EventType
 )
 VALUES
     (
         "a1w2600000FxwrzAAB",
         STRUCT
             <entityName STRING,
              recordIds	ARRAY<STRING>,
              _changeType	STRING,
              _changedFields	ARRAY<STRING>,
              changeOrigin	STRING,
              transactionKey	STRING,
              sequenceNumber	INTEGER,
              commitTimestamp	INTEGER,
              commitUser	STRING,
              commitNumber INTEGER
                 >(
             'entityName',
             ["a1w2600000FxwrzAAB"],
             "INSERT",
             ["LastModifiedDate"],
             "com/salesforce/api/soap/56.0;client=SfdcInternalAPI/",
             "0001dcd1-98ee-76c7-76c8-502452548cff",
             1,
             1671458063000,
             "00526000009uyrWAAQ",
             11010485985695
             )
         ,
         'STRING3', -- Id
         FALSE, -- IsDeleted
         'STRING1', -- Name
         NULL, -- CurrencyIsoCode
         1671537998000, -- CreatedDate
         'STRING', -- CreatedById
         1671537998000, -- LastModifiedDate
         'STRING', -- LastModifiedById
         1671537998000, -- SystemModstamp
         1671537998000, -- LastActivityDate
         'STRING', -- ConnectionReceivedId
         'STRING', -- ConnectionSentId
         'STRING', -- LLC_BI__Covenant2__c
         'STRING', -- LLC_BI__Loan__c
         FALSE, -- LLC_BI__Active__c
         'STRING', -- CCS_UserProfile__c
         NULL, -- CCS_Restricted_User__c
         "OBJECTTYPE",
         "EVENTTYPE"
     );

 INSERT INTO dmn01-rsksoi-bld-01-2017.dmn01_rsksoi_euwe2_rsk_csp_downstream_raw.rskcsp_ds_loan_covenant  --  INSERT 3
 (
     ReplayId,
     ChangeEventHeader,
     Id,
     IsDeleted,
     Name,
     CurrencyIsoCode,
     CreatedDate,
     CreatedById,
     LastModifiedDate,
     LastModifiedById,
     SystemModstamp,
     LastActivityDate,
     ConnectionReceivedId,
     ConnectionSentId,
     LLC_BI__Covenant2__c,
     LLC_BI__Loan__c,
     LLC_BI__Active__c,
     CCS_UserProfile__c,
     CCS_Restricted_User__c,
     _ObjectType,
     _EventType
 )
 VALUES
     (
         "a1w2600000FxwrzAAB",
         STRUCT
             <entityName STRING,
              recordIds	ARRAY<STRING>,
              _changeType	STRING,
              _changedFields	ARRAY<STRING>,
              changeOrigin	STRING,
              transactionKey	STRING,
              sequenceNumber	INTEGER,
              commitTimestamp	INTEGER,
              commitUser	STRING,
              commitNumber INTEGER
                 >(
             'entityName',
             ["a1w2600000FxwrzAAB"],
             "DELETE",
             ["LastModifiedDate"],
             "com/salesforce/api/soap/56.0;client=SfdcInternalAPI/",
             "0001dcd1-98ee-76c7-76c8-502452548cff",
             1,
             1671458063000,
             "00526000009uyrWAAQ",
             11010485985695
             )
         ,
         'STRING3', -- Id
         FALSE, -- IsDeleted
         'STRING1', -- Name
         NULL, -- CurrencyIsoCode
         1671537998000, -- CreatedDate
         'STRING', -- CreatedById
         1671537998000, -- LastModifiedDate
         'STRING', -- LastModifiedById
         1671537998000, -- SystemModstamp
         1671537998000, -- LastActivityDate
         'STRING', -- ConnectionReceivedId
         'STRING', -- ConnectionSentId
         'STRING', -- LLC_BI__Covenant2__c
         'STRING', -- LLC_BI__Loan__c
         FALSE, -- LLC_BI__Active__c
         'STRING', -- CCS_UserProfile__c
         NULL, -- CCS_Restricted_User__c
         "OBJECTTYPE",
         "EVENTTYPE"
     );

 INSERT INTO dmn01-rsksoi-bld-01-2017.dmn01_rsksoi_euwe2_rsk_csp_downstream_raw.rskcsp_ds_loan_covenant  --  MANDATORY FILED CHECK
 (
     ReplayId,
     ChangeEventHeader,
     Id,
     IsDeleted,
     Name,
     CurrencyIsoCode,
     CreatedDate,
     CreatedById,
     LastModifiedDate,
     LastModifiedById,
     SystemModstamp,
     LastActivityDate,
     ConnectionReceivedId,
     ConnectionSentId,
     LLC_BI__Covenant2__c,
     LLC_BI__Loan__c,
     LLC_BI__Active__c,
     CCS_UserProfile__c,
     CCS_Restricted_User__c,
     _ObjectType,
     _EventType
 )
 VALUES
     (
         "a1w2600000FxwrzAAB",
         STRUCT
             <entityName STRING,
              recordIds	ARRAY<STRING>,
              _changeType	STRING,
              _changedFields	ARRAY<STRING>,
              changeOrigin	STRING,
              transactionKey	STRING,
              sequenceNumber	INTEGER,
              commitTimestamp	INTEGER,
              commitUser	STRING,
              commitNumber INTEGER
                 >(
             'entityName',
             ["a1w2600000FxwrzAAB"],
             "INSERT",
             ["LastModifiedDate"],
             "com/salesforce/api/soap/56.0;client=SfdcInternalAPI/",
             "0001dcd1-98ee-76c7-76c8-502452548cff",
             1,
             1671458063000,
             "00526000009uyrWAAQ",
             11010485985695
             )
         ,
         'STRING4', -- Id
         FALSE, -- IsDeleted
         'STRING5', -- Name
         NULL, -- CurrencyIsoCode
         NULL, -- CreatedDate
         'STRING', -- CreatedById
         NULL, -- LastModifiedDate
         'STRING', -- LastModifiedById
         1671537998000, -- SystemModstamp
         1671537998000, -- LastActivityDate
         'STRING', -- ConnectionReceivedId
         'STRING', -- ConnectionSentId
         'STRING', -- LLC_BI__Covenant2__c
         'STRING', -- LLC_BI__Loan__c
         FALSE, -- LLC_BI__Active__c
         'STRING', -- CCS_UserProfile__c
         NULL, -- CCS_Restricted_User__c
         "OBJECTTYPE",
         "EVENTTYPE"
     );

 INSERT INTO dmn01-rsksoi-bld-01-2017.dmn01_rsksoi_euwe2_rsk_csp_downstream_raw.rskcsp_ds_loan_covenant  --  Length FILED CHECK
 (
     ReplayId,
     ChangeEventHeader,
     Id,
     IsDeleted,
     Name,
     CurrencyIsoCode,
     CreatedDate,
     CreatedById,
     LastModifiedDate,
     LastModifiedById,
     SystemModstamp,
     LastActivityDate,
     ConnectionReceivedId,
     ConnectionSentId,
     LLC_BI__Covenant2__c,
     LLC_BI__Loan__c,
     LLC_BI__Active__c,
     CCS_UserProfile__c,
     CCS_Restricted_User__c,
     _ObjectType,
     _EventType
 )
 VALUES
     (
         "a1w2600000FxwrzAAB",
         STRUCT
             <entityName STRING,
              recordIds	ARRAY<STRING>,
              _changeType	STRING,
              _changedFields	ARRAY<STRING>,
              changeOrigin	STRING,
              transactionKey	STRING,
              sequenceNumber	INTEGER,
              commitTimestamp	INTEGER,
              commitUser	STRING,
              commitNumber INTEGER
                 >(
             'entityName',
             ["a1w2600000FxwrzAAB"],
             "INSERT",
             ["LastModifiedDate"],
             "com/salesforce/api/soap/56.0;client=SfdcInternalAPI/",
             "0001dcd1-98ee-76c7-76c8-502452548cff",
             1,
             1671458063000,
             "00526000009uyrWAAQ",
             11010485985695
             )
         ,
         'STRING4STRING4STRING4STRING4STRING4STRING4STRING4', -- Id
         FALSE, -- IsDeleted
         'STRING5', -- Name
         NULL, -- CurrencyIsoCode
         1671537998000, -- CreatedDate
         'STRING', -- CreatedById
         1671537998000, -- LastModifiedDate
         'STRING', -- LastModifiedById
         1671537998000, -- SystemModstamp
         1671537998000, -- LastActivityDate
         'STRING', -- ConnectionReceivedId
         'STRING', -- ConnectionSentId
         'STRING', -- LLC_BI__Covenant2__c
         'STRING', -- LLC_BI__Loan__c
         FALSE, -- LLC_BI__Active__c
         'STRING', -- CCS_UserProfile__c
         NULL, -- CCS_Restricted_User__c
         "OBJECTTYPE",
         "EVENTTYPE"
     );

-- undelete check

 INSERT INTO dmn01-rsksoi-bld-01-2017.dmn01_rsksoi_euwe2_rsk_csp_downstream_raw.rskcsp_ds_loan_covenant  --  INSERT
 (
     ReplayId,
     ChangeEventHeader,
     Id,
     IsDeleted,
     Name,
     CurrencyIsoCode,
     CreatedDate,
     CreatedById,
     LastModifiedDate,
     LastModifiedById,
     SystemModstamp,
     LastActivityDate,
     ConnectionReceivedId,
     ConnectionSentId,
     LLC_BI__Covenant2__c,
     LLC_BI__Loan__c,
     LLC_BI__Active__c,
     CCS_UserProfile__c,
     CCS_Restricted_User__c,
     _ObjectType,
     _EventType
 )
 VALUES
     (
         "a1w2600000FxwrzAAB",
         STRUCT
             <entityName STRING,
              recordIds	ARRAY<STRING>,
              _changeType	STRING,
              _changedFields	ARRAY<STRING>,
              changeOrigin	STRING,
              transactionKey	STRING,
              sequenceNumber	INTEGER,
              commitTimestamp	INTEGER,
              commitUser	STRING,
              commitNumber INTEGER
                 >(
             'entityName',
             ["a1w2600000FxwrzAAB"],
             "INSERT",
             ["LastModifiedDate"],
             "com/salesforce/api/soap/56.0;client=SfdcInternalAPI/",
             "0001dcd1-98ee-76c7-76c8-502452548cff",
             1,
             1671458063000,
             "00526000009uyrWAAQ",
             11010485985695
             )
         ,
         'undelete', -- Id
         FALSE, -- IsDeleted
         'STRING', -- Name
         NULL, -- CurrencyIsoCode
         1671537998000, -- CreatedDate
         'STRING', -- CreatedById
         1671537998000, -- LastModifiedDate
         'STRING', -- LastModifiedById
         1671537998000, -- SystemModstamp
         1671537998000, -- LastActivityDate
         'STRING', -- ConnectionReceivedId
         'STRING', -- ConnectionSentId
         'STRING', -- LLC_BI__Covenant2__c
         'STRING', -- LLC_BI__Loan__c
         FALSE, -- LLC_BI__Active__c
         'STRING', -- CCS_UserProfile__c
         NULL, -- CCS_Restricted_User__c
         "OBJECTTYPE",
         "EVENTTYPE"
     );

 INSERT INTO dmn01-rsksoi-bld-01-2017.dmn01_rsksoi_euwe2_rsk_csp_downstream_raw.rskcsp_ds_loan_covenant  --  INSERT
 (
     ReplayId,
     ChangeEventHeader,
     Id,
     IsDeleted,
     Name,
     CurrencyIsoCode,
     CreatedDate,
     CreatedById,
     LastModifiedDate,
     LastModifiedById,
     SystemModstamp,
     LastActivityDate,
     ConnectionReceivedId,
     ConnectionSentId,
     LLC_BI__Covenant2__c,
     LLC_BI__Loan__c,
     LLC_BI__Active__c,
     CCS_UserProfile__c,
     CCS_Restricted_User__c,
     _ObjectType,
     _EventType
 )
 VALUES
     (
         "a1w2600000FxwrzAAB",
         STRUCT
             <entityName STRING,
              recordIds	ARRAY<STRING>,
              _changeType	STRING,
              _changedFields	ARRAY<STRING>,
              changeOrigin	STRING,
              transactionKey	STRING,
              sequenceNumber	INTEGER,
              commitTimestamp	INTEGER,
              commitUser	STRING,
              commitNumber INTEGER
                 >(
             'entityName',
             ["a1w2600000FxwrzAAB"],
             "DELETE",
             ["LastModifiedDate"],
             "com/salesforce/api/soap/56.0;client=SfdcInternalAPI/",
             "0001dcd1-98ee-76c7-76c8-502452548cff",
             1,
             1671458063000,
             "00526000009uyrWAAQ",
             11010485985695
             )
         ,
         'undelete', -- Id
         FALSE, -- IsDeleted
         'STRING', -- Name
         NULL, -- CurrencyIsoCode
         1671537998000, -- CreatedDate
         'STRING', -- CreatedById
         1671537998000, -- LastModifiedDate
         'STRING', -- LastModifiedById
         1671537998000, -- SystemModstamp
         1671537998000, -- LastActivityDate
         'STRING', -- ConnectionReceivedId
         'STRING', -- ConnectionSentId
         'STRING', -- LLC_BI__Covenant2__c
         'STRING', -- LLC_BI__Loan__c
         FALSE, -- LLC_BI__Active__c
         'STRING', -- CCS_UserProfile__c
         NULL, -- CCS_Restricted_User__c
         "OBJECTTYPE",
         "EVENTTYPE"
     );
 INSERT INTO dmn01-rsksoi-bld-01-2017.dmn01_rsksoi_euwe2_rsk_csp_downstream_raw.rskcsp_ds_loan_covenant  --  INSERT
 (
     ReplayId,
     ChangeEventHeader,
     Id,
     IsDeleted,
     Name,
     CurrencyIsoCode,
     CreatedDate,
     CreatedById,
     LastModifiedDate,
     LastModifiedById,
     SystemModstamp,
     LastActivityDate,
     ConnectionReceivedId,
     ConnectionSentId,
     LLC_BI__Covenant2__c,
     LLC_BI__Loan__c,
     LLC_BI__Active__c,
     CCS_UserProfile__c,
     CCS_Restricted_User__c,
     _ObjectType,
     _EventType
 )
 VALUES
     (
         "a1w2600000FxwrzAAB",
         STRUCT
             <entityName STRING,
              recordIds	ARRAY<STRING>,
              _changeType	STRING,
              _changedFields	ARRAY<STRING>,
              changeOrigin	STRING,
              transactionKey	STRING,
              sequenceNumber	INTEGER,
              commitTimestamp	INTEGER,
              commitUser	STRING,
              commitNumber INTEGER
                 >(
             'entityName',
             ["a1w2600000FxwrzAAB"],
             "UNDELETE",
             ["LastModifiedDate"],
             "com/salesforce/api/soap/56.0;client=SfdcInternalAPI/",
             "0001dcd1-98ee-76c7-76c8-502452548cff",
             1,
             1671458063000,
             "00526000009uyrWAAQ",
             11010485985695
             )
         ,
         'undelete', -- Id
         FALSE, -- IsDeleted
         'STRING', -- Name
         NULL, -- CurrencyIsoCode
         1671537998000, -- CreatedDate
         'STRING', -- CreatedById
         1671537998000, -- LastModifiedDate
         'STRING', -- LastModifiedById
         1671537998000, -- SystemModstamp
         1671537998000, -- LastActivityDate
         'STRING', -- ConnectionReceivedId
         'STRING', -- ConnectionSentId
         'STRING', -- LLC_BI__Covenant2__c
         'STRING', -- LLC_BI__Loan__c
         FALSE, -- LLC_BI__Active__c
         'STRING', -- CCS_UserProfile__c
         NULL, -- CCS_Restricted_User__c
         "OBJECTTYPE",
         "EVENTTYPE"
     );

 INSERT INTO dmn01-rsksoi-bld-01-2017.dmn01_rsksoi_euwe2_rsk_csp_downstream_raw.rskcsp_ds_loan_covenant  --  INSERT
 (
     ReplayId,
     ChangeEventHeader,
     Id,
     IsDeleted,
     Name,
     CurrencyIsoCode,
     CreatedDate,
     CreatedById,
     LastModifiedDate,
     LastModifiedById,
     SystemModstamp,
     LastActivityDate,
     ConnectionReceivedId,
     ConnectionSentId,
     LLC_BI__Covenant2__c,
     LLC_BI__Loan__c,
     LLC_BI__Active__c,
     CCS_UserProfile__c,
     CCS_Restricted_User__c,
     _ObjectType,
     _EventType
 )
 VALUES
     (
         "a1w2600000FxwrzAAB",
         STRUCT
             <entityName STRING,
              recordIds	ARRAY<STRING>,
              _changeType	STRING,
              _changedFields	ARRAY<STRING>,
              changeOrigin	STRING,
              transactionKey	STRING,
              sequenceNumber	INTEGER,
              commitTimestamp	INTEGER,
              commitUser	STRING,
              commitNumber INTEGER
                 >(
             'entityName',
             ["a1w2600000FxwrzAAB"],
             "UNDELETE",
             ["LastModifiedDate"],
             "com/salesforce/api/soap/56.0;client=SfdcInternalAPI/",
             "0001dcd1-98ee-76c7-76c8-502452548cff",
             1,
             1671458063000,
             "00526000009uyrWAAQ",
             11010485985695
             )
         ,
         'STRING11', -- Id
         FALSE, -- IsDeleted
         'STRING', -- Name
         NULL, -- CurrencyIsoCode
         1671537998000, -- CreatedDate
         'STRING', -- CreatedById
         1671537998000, -- LastModifiedDate
         'STRING', -- LastModifiedById
         1671537998000, -- SystemModstamp
         1671537998000, -- LastActivityDate
         'STRING', -- ConnectionReceivedId
         'STRING', -- ConnectionSentId
         'STRING', -- LLC_BI__Covenant2__c
         'STRING', -- LLC_BI__Loan__c
         FALSE, -- LLC_BI__Active__c
         'STRING', -- CCS_UserProfile__c
         NULL, -- CCS_Restricted_User__c
         "OBJECTTYPE",
         "EVENTTYPE"
     );